{"name": "Проверка ответа на запрос изменения данных неаутентифицированного пользователя", "status": "passed", "start": 1725695815573, "stop": 1725695815925, "uuid": "90205ba9-b912-4aa7-b908-e108325d0ff2", "historyId": "15ddd7987c2e5999e579e59a038213af", "testCaseId": "15ddd7987c2e5999e579e59a038213af", "fullName": "tests.test_user_update.TestUserUpdate#test_update_user_unauthenticated_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_update"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "DESKTOP-82VEM3U"}, {"name": "thread", "value": "8332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_update"}]}